language: java
sudo: required

# We need Docker.
services:
  - docker

# Required packages.
# Besides, packages may depend on snapshots.
# So, we must be able to find them at Sonatype.
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y wget rpm
  - wget http://roboconf.net/resources/build/settings.xml

# Skip the default Maven command launched by Travis.
# By default, it is "mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
install: true

# Build with Maven.
script:
  - mvn package --settings settings.xml && ./tests/run-tests-in-docker.sh

# Actions to perform after the build.
after_success:
  - ./upload-to-sonatype.sh
  - ./upload-to-bintray.sh
